### PR TITLE
Fix get-cli.sh script to point to correct windows assest

### PR DESCRIPTION
**Pull request by BMartinos**
The get-cli.sh script was pointing to an incorrect windows assets, and was never updating/downloading the windows version correctly.

https://github.com/openhie/instant-v2/releases/
https://github.com/openhie/instant-v2/releases/download/2.3.1/instant-win.exe

### CODE REVIEW

**Comment by arran-standish** [comment]
It might be better to output a warning to instead consider using WSL if they try download the windows binary. Since the majority of images used in platform assume a Linux base and don't actually have a valid windows image it can use. Might give the wrong assumption.

**Comment by arran-standish** [comment]
Also if you are changing the get-cli.sh file it would be nice opportunity to update the root url for all links to https://github.com/openhie/instant-v2/ instead. It does have a redirect rule currently so it is not an issue but would make it more consistent.

**Comment by BMartinos** [comment]
> bf98379

Updated in [bf98379](https://github.com/jembi/platform/pull/286/commits/bf983791304281bfe3b30abd87d481ba35ee920b)

**Comment by BMartinos** [comment]
For the WSL related comment, Good suggestion, Ill leave that enhancement to the Platform team to update. If there are packages which currently dont run on Windows base image, it might be better to not have a windows based installer, but there might be reason its still needed which im not familiar with

**Review by arran-standish — APPROVED** [review]

**Review by rcrichton — APPROVED** [review]

**Comment by rcrichton** [comment]
On the windows issue. I think docker desktop supports WSL so a windows binary still might make sense. We would need someone to try this out however. At one stage we were able to get it to work but I think we need to revise.

**Comment by rcrichton** [comment]
Also, I think instead of fetching the cli and have it sitting in the working directory, people should be installing instant on their machine like any other CLI as described ehre - https://jembi.gitbook.io/instant-v2/getting-started/quick-start

Maybe we can get rid of this script all together.

**Comment by BMartinos** [comment]
> Also, I think instead of fetching the cli and have it sitting in the working directory, people should be installing instant on their machine like any other CLI as described ehre - https://jembi.gitbook.io/instant-v2/getting-started/quick-start
> 
> Maybe we can get rid of this script all together.

Also a good idea :+1: 

Maybe taking this further, instead of removing the script, repurpose it to instead of installing the binary in the directory root, but to rather have the script install/update the the binary (of choice) for global CLI usage, as described in the quick start steps

**Pull request merged**
