### PR TITLE
Cu 86bygcqxd images placement for data store dashboards monitoring

### PR DESCRIPTION
**Pull request by brett-onions**
## Summary by CodeRabbit

- **New Features**
  - Added a new test case for the CDR recipe in the testing workflow.

- **Improvements**
  - Updated `postgres-metastore` service to use a variable for the image version, enhancing flexibility and maintainability.

- **Chores**
  - Environment variables for `SS_POSTGRES_IMAGE` and `POSTGRES_METASTORE` added to package metadata.
  - Refactored the test script to use a function for running different tests, improving code organization and readability.

### CODE REVIEW

**Comment by rcrichton** [comment]
Task linked: [CU-86bygcqxd Images Placement for DataStore Dashboards Monitoring](https://app.clickup.com/t/86bygcqxd)

**Review by drizzentic — APPROVED** [review]
LGTM!

**Comment by rcrichton** [comment]
@coderabbitai review

**Review by BMartinos — APPROVED** [review]
LGTM :+1:

**Review by bradsawadye — APPROVED** [review]

**Pull request merged**
