### PR TITLE
Remove ansible vault requirement

### PR DESCRIPTION
**Pull request by BMartinos**
The Vault is no longer needed as the docker login is also not needed to execute the ansible script.
This is currently also a blocker for anyone wanting to use ansible to provision the servers and they dont have access to keepass to retrieve the vault password

Additional update was to make the default user configurable within the inventory. It was assumed the default user will always be `ubuntu`, and statically adding the `ubuntu` user to the docker group. This is now part of the docker_users list to dynamically define/update the default user in use

## Summary by CodeRabbit

- **Documentation**
	- Updated Ansible playbook instructions by removing `--ask-vault-pass` option and eliminating Vault and Keepass sections.

- **New Features**
	- Added a user with username `ubuntu` to the `docker_users` list.

- **Refactor**
	- Simplified Ansible roles by removing tasks related to `ubuntu` user management and Docker Hub login.
	- Added a task to create Docker daemon config path if it doesn't exist.

- **Chores**
	- Removed Docker Hub login credentials from configuration files.

### CODE REVIEW

**Review by rcrichton — APPROVED** [review]
LGTM, has this been tested a proved working with a platform deploy done? I didn't run this myself.

**Comment by BMartinos** [comment]
Hi @rcrichton Ive tested this successfully within my local environment making use of a local VM to run the ansible script against. Below is a screencast of this being tested (making use of a multipass VM instance)

[Screencast from 08-05-2024 10:05:23.webm](https://github.com/jembi/platform/assets/7311421/c315b134-fc62-4891-9a42-7d1821f28786)

**Comment by rcrichton** [comment]
@coderabbitai review

**Review by rcrichton — APPROVED** [review]
LGTM

**Pull request merged**
